### PR TITLE
Move to W3C CCG

### PR DESCRIPTION
**Pull request by clehner**
Work item proposal accepted: https://github.com/w3c-ccg/community/issues/194

### CODE REVIEW

**Comment by mirceanis** [comment]
@clehner what would be the next steps here?
I see that there is already a repository at https://github.com/w3c-ccg/ethereum-eip712-signature-2021-spec/ with roughly the same contents.

I would assume it is easiest to transfer this repository to the w3c-ccg org, but for that to happen, the one already there must be deleted.

**Review by mirceanis — APPROVED** [review]
looks good.

we can merge this first thing after the transfer, but the target repo needs to be renamed or deleted before the transfer can happen.

**Comment by clehner** [comment]
@mirceanis it's been renamed; can you initiate transfer?

**Comment by clehner** [comment]
Transfer has been done; this PR should be ready for review/merging now

**Pull request merged**
